"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { Activity, AlertTriangle, Bell, BrainCircuit, ChevronRight, LayoutDashboard, LogOut, Menu, Search, Settings, ShieldAlert, UserRound, Users, X, FileWarning } from "lucide-react";
import { useState } from "react";
import { useAuth } from "@/context/AuthContext";
const navigation = [["Monitoring", [["Dashboard", "/dashboard", LayoutDashboard], ["Logs", "/logs", Activity], ["Anomalies", "/anomalies", AlertTriangle]]], ["Security", [["Incidents", "/incidents", ShieldAlert], ["Security events", "/security-events", FileWarning]]], ["Intelligence", [["AI analysis", "/ai-analysis", BrainCircuit]]], ["System", [["Notifications", "/notifications", Bell], ["Users", "/users", Users], ["Settings", "/settings", Settings]]]] as const;
function Nav({ close }: { close?: () => void }) { const pathname = usePathname(); const { user, logout } = useAuth(); return <aside className="flex h-full w-72 flex-col border-r border-slate-800/80 bg-[#0d1423] px-4 py-5"><Link href="/dashboard" onClick={close} className="mb-8 flex items-center gap-3 px-3"><span className="grid size-9 place-items-center rounded-xl bg-cyan-400/10 text-cyan-300 ring-1 ring-cyan-400/20"><Activity size={20}/></span><span className="text-lg font-bold tracking-[.18em] text-white">LOGIQ</span></Link><nav className="flex-1 space-y-6">{navigation.map(([group, links]) => <section key={group}><p className="px-3 pb-2 text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">{group}</p><div className="space-y-1">{links.map(([name, href, Icon]) => { const active = pathname === href || (href !== "/dashboard" && pathname.startsWith(href)); return <Link key={href} href={href} onClick={close} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition ${active ? "bg-cyan-400/10 text-cyan-300 ring-1 ring-cyan-400/15" : "text-slate-400 hover:bg-slate-800/70 hover:text-slate-100"}`}><Icon size={17}/>{name}</Link>})}</div></section>)}</nav><div className="border-t border-slate-800 pt-4"><Link href="/profile" onClick={close} className="mb-2 flex items-center gap-3 rounded-lg px-3 py-2 text-sm text-slate-400 hover:bg-slate-800"><UserRound size={17}/>Profile</Link><button onClick={logout} className="flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm text-slate-400 hover:bg-red-500/10 hover:text-red-300"><LogOut size={17}/>Logout</button>{user && <p className="mt-3 truncate px-3 text-xs text-slate-500">{user.email}</p>}</div></aside> }
export function AppShell({ children }: { children: React.ReactNode }) { const pathname = usePathname(); const router = useRouter(); const { user } = useAuth(); const [open, setOpen] = useState(false); if (pathname === "/login" || pathname === "/register") return <>{children}</>; const title = pathname.split("/").filter(Boolean).at(-1)?.replaceAll("-", " ") || "dashboard"; return <div className="min-h-screen bg-[#080d18] text-slate-200"><div className="fixed inset-y-0 left-0 z-30 hidden lg:block"><Nav/></div>{open && <div className="fixed inset-0 z-50 flex lg:hidden"><div className="w-72"><Nav close={() => setOpen(false)}/></div><button aria-label="Close navigation" onClick={() => setOpen(false)} className="flex-1 bg-slate-950/70"><X className="m-4 text-white"/></button></div>}<main className="lg:pl-72"><header className="sticky top-0 z-20 flex h-16 items-center gap-4 border-b border-slate-800/80 bg-[#080d18]/90 px-4 backdrop-blur lg:px-8"><button className="lg:hidden" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu/></button><div className="min-w-0 flex-1"><h1 className="capitalize text-base font-semibold text-white">{title}</h1><p className="hidden text-xs text-slate-500 sm:block">Security operations workspace</p></div><button className="hidden items-center gap-2 rounded-lg border border-slate-800 bg-slate-900/70 px-3 py-2 text-sm text-slate-500 md:flex" onClick={() => router.push("/logs")}><Search size={15}/>Search logs <ChevronRight size={14}/></button><Link href="/notifications" className="relative rounded-lg p-2 text-slate-400 hover:bg-slate-800 hover:text-white"><Bell size={19}/></Link><Link href="/profile" className="flex items-center gap-2 rounded-lg p-1.5 hover:bg-slate-800"><span className="grid size-7 place-items-center rounded-full bg-cyan-400/10 text-xs font-bold text-cyan-300">{user?.name?.slice(0,2).toUpperCase() || "--"}</span><span className="hidden text-left text-xs sm:block"><b className="block max-w-28 truncate text-slate-200">{user?.name || "Account"}</b><em className="not-italic text-slate-500">{user?.role || ""}</em></span></Link></header><div className="mx-auto max-w-[1600px] p-4 sm:p-6 lg:p-8">{children}</div></main></div> }
